<a href="https://colab.research.google.com/github/111718105068/ranjith/blob/main/day9_practice_exercies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# Dataset
olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])
olympic_country_silver = np.array([17, 28, 25, 28, 8, 14, 11])
olympic_country_bronze = np.array([19, 22, 32, 29, 7, 17, 14])

# 1. Find the country index with the maximum gold
max_gold_index = np.argmax(olympic_country_gold)

# 2. Print the country with the maximum gold
country_with_max_gold = olympic_country[max_gold_index]
print("Country with Maximum Gold:", country_with_max_gold)

# 3. Find countries with more than 20 gold
countries_with_more_than_20_gold = olympic_country[olympic_country_gold > 20]
print("Countries with more than 20 Gold:", countries_with_more_than_20_gold)

# 4.Evaluate the dataset and print the medals:
total_medals = olympic_country_gold + olympic_country_silver + olympic_country_bronze

# 1. Print each country name with the number of gold medals
for i in range(len(olympic_country)):
    print(f"{olympic_country[i]} - Gold Medals: {olympic_country_gold[i]}")

# 2. Print each country name with the total number of medals
for i in range(len(olympic_country)):
    print(f"{olympic_country[i]} - Total Medals: {total_medals[i]}")


Country with Maximum Gold: US
Countries with more than 20 Gold: ['GBR' 'China' 'RUS' 'US']
GBR - Gold Medals: 29
China - Gold Medals: 38
RUS - Gold Medals: 24
US - Gold Medals: 46
KOR - Gold Medals: 13
JPN - Gold Medals: 7
GER - Gold Medals: 11
GBR - Total Medals: 65
China - Total Medals: 88
RUS - Total Medals: 81
US - Total Medals: 103
KOR - Total Medals: 28
JPN - Total Medals: 38
GER - Total Medals: 36


# 1. Create a 3x3x3 array with random values

In [4]:
import numpy as np
random_array = np.random.rand(3, 3, 3)
print(random_array)


[[[0.96976892 0.10867972 0.76986967]
  [0.66094704 0.83783109 0.7218387 ]
  [0.92752031 0.34887191 0.44603386]]

 [[0.82530319 0.99139393 0.1426972 ]
  [0.15550119 0.25663573 0.22241814]
  [0.38750795 0.3288461  0.79265271]]

 [[0.14769995 0.65135676 0.45757092]
  [0.95769996 0.90612808 0.32784331]
  [0.81346405 0.17337667 0.43878024]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [7]:
import numpy as np
matrix = np.diag(1 + np.arange(4), k=-1)
print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [8]:
import numpy as np
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [9]:
import numpy as np
random_matrix = np.random.rand(5, 5)
normalized_matrix = (random_matrix - random_matrix.min()) / (random_matrix.max() - random_matrix.min())
print(normalized_matrix)


[[0.32725492 0.85417589 0.40392289 0.12759063 0.31147349]
 [0.09842364 0.19767669 0.02371186 0.16856115 0.87362668]
 [0.         0.9171215  0.75592521 0.76979245 0.60917395]
 [0.33190195 0.4513401  0.95142485 0.02752385 0.34483906]
 [0.32799245 0.44896507 0.1269251  1.         0.88262722]]


# 5. How to find common values between two arrays?

In [10]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
common_values = np.intersect1d(array1, array2)
print(common_values)


[3 4 5]


# 6. How to get the dates of yesterday, today and tomorrow?

In [11]:
from datetime import datetime, timedelta

today = datetime.now()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday.strftime("%Y-%m-%d"))
print("Today:", today.strftime("%Y-%m-%d"))
print("Tomorrow:", tomorrow.strftime("%Y-%m-%d"))


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7. Consider two random array A and B, check if they are equal

In [13]:
import numpy as np
A = np.array([1, 2, 3])
B = np.array([1, 2, 3,4])
are_equal = np.array_equal(A, B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Arrays A and B are not equal.


# 8.Create random vector of size 10 and replace the maximum value by 0

In [14]:
import numpy as np
random_vector = np.random.rand(10)
max_value_index = np.argmax(random_vector)
random_vector[max_value_index] = 0
print(random_vector)


[0.77888389 0.74244377 0.02946233 0.         0.19664465 0.10311636
 0.02909245 0.48020437 0.67302053 0.01956081]


# 9. How to print all the values of an array?

In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
for value in arr:
    print(value)


1
2
3
4
5


# **10.Subtract the mean of each row of a matrix**

In [16]:
import numpy as np
mat = np.random.rand(3, 3)  # Replace with your matrix
row_means = np.mean(mat, axis=1)
result = mat - row_means[:, np.newaxis]
print(result)


[[-0.1651407   0.1818472  -0.0167065 ]
 [ 0.118241    0.29139001 -0.409631  ]
 [-0.2669139   0.34449004 -0.07757615]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [17]:
import numpy as np
A = np.array([1, 2, 3, 4, 5])
B = np.array([1, 3, 4])  # Indices where you want to add 1
A[B] += 1
print(A)


[1 3 3 5 6]


# 12.How to get the diagonal of a dot product?

In [18]:
import numpy as np
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
result = np.diag(np.dot(A, B))
print(result)


[1.06779502 0.31746478 0.23787339]


# 13.How to find the most frequent value in an array?

In [23]:
import numpy as np

x = np.random.randint(0, 10, 50)  # Assuming you have your array

# Use bincount to count occurrences of each value in x
counts = np.bincount(x)

# Find the value with the maximum count
most_frequent_value = np.argmax(counts)

print("Most frequent value:", most_frequent_value)


Most frequent value: 6


# 14.How to get the n largest values of an array

In [24]:
import numpy as np

arr = np.array([23, 45, 12, 67, 89, 34])
n = 3  # Number of largest values you want to retrieve
indices = np.argsort(arr)[::-1][:n]
largest_values = arr[indices]

print("N largest values:", largest_values)


N largest values: [89 67 45]


# 15.How to create a record array from a regular array?

In [25]:
import numpy as np

regular_array = np.array([("Alice", 25), ("Bob", 30), ("Charlie", 35)], dtype=[('name', 'U10'), ('age', int)])
record_array = np.rec.array(regular_array)

print(record_array)


[('Alice', 25) ('Bob', 30) ('Charlie', 35)]


# 16. How to swap two rows of an array?

In [26]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Swap rows 0 and 1
arr[[0, 1]] = arr[[1, 0]]

print(arr)


[[4 5 6]
 [1 2 3]
 [7 8 9]]


# 17. Write python code to reshape to the next dimension of numpy array?

In [27]:
import numpy as np

x = np.array([[23, 34, 121],
              [23, 22, 67],
              [686, 434, 123]])

# Reshape to the next dimension
reshaped_array = x.reshape(-1)

print(reshaped_array)


[ 23  34 121  23  22  67 686 434 123]
